import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "./styles/layout.scss";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="app">
      <div className="main">{children}</div>
    </div>
  );
}
